// <auto-generated />
using Core_Api_Demo.DataAccsessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Core_Api_Demo.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core_Api_Demo.DataAccsessLayer.Isciler", b =>
                {
                    b.Property<int>("IsciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IsciAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsciSoyad")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IsciID");

                    b.ToTable("Iscilers");
                });
#pragma warning restore 612, 618
        }
    }
}
